### ISSUE TITLE
How to run Dredd using .apib file stored in Gitlab?

### ISSUE THREAD

**Issue by KonstantinxVx** [apiaryio/dredd#1017]
#### Describe your problem
I have my **public.apib** file stored in Gitlab.
How can I define this in my **dredd.yml** file?
I've tried to put on `blueprint: ` field the gitlab https link, but it seems to be not working.  

#### What command line options do you use?

```
$ dredd 
```

#### What is in your `dredd.yml`?

```yaml
    reporter: apiary
    custom:
      apiaryApiKey: <ApiKey>
      apiaryApiName: <ApiName>
    dry-run: null
    hookfiles: null
    language: nodejs
    sandbox: false
    server: null
    server-wait: 3
    init: false
    names: false
    only: []
    output: []
    header: []
    sorted: false
    user: null
    inline-errors: false
    details: false
    method: []
    color: true
    level: info
    timestamp: false
    silent: false
    path: []
    hooks-worker-timeout: 5000
    hooks-worker-connect-timeout: 1500
    hooks-worker-connect-retry: 500
    hooks-worker-after-connect-wait: 100
    hooks-worker-term-timeout: 5000
    hooks-worker-term-retry: 500
    hooks-worker-handler-host: 127.0.0.1
    hooks-worker-handler-port: 61321
    config: ./dredd.yml
    blueprint: 'https://gitlab.<my-company>.com/<path-to-docs>/public.apib'
    endpoint: 'https://<my-api>.apiary-mock.com/' 
```

#### What's your `dredd --version` output?

```
dredd v4.6.2 (Darwin 17.5.0; x64)
```

**Comment by honzajavorek** [comment]
Does `dredd https://gitlab.<my-company>.com/<path-to-docs>/public.apib https://<my-api>.apiary-mock.com/` work for you? Fetching from URL should work.

Could you put a dummy blueprint file on GitLab the same way and post it here so we could inspect how exactly GitLab serves the file, which headers, etc.?

**Comment by honzajavorek** [comment]
I went to the GitLab page representing the file and clicked the <kbd>Open raw</kbd> icon in the top right. I got following address pointing at the raw document:

```
https://gitlab.com/Voyku/apib-dredd/raw/master/api-description.apib
```

I was then able to successfully run Dredd without `dredd.yml` like this:

```
dredd https://gitlab.com/Voyku/apib-dredd/raw/master/api-description.apib http://localhost:5000
```

Then I tried to modify `dredd.yml` to contain following and I was able to successfully run Dredd as well:

```yaml
...
blueprint: 'https://gitlab.com/Voyku/apib-dredd/raw/master/api-description.apib'
endpoint: 'http://localhost:5000'
...
```
