### ISSUE TITLE
How can I use few reporters 

### ISSUE THREAD

**Issue by KonstantinxVx** [apiaryio/dredd#1020]
#### Describe your problem

Hello there,

Please advise, what I have to do in the case when I need to use 2 reporters: `apiary reporter` and `xunit`. What do I need to specify in my `dredd.yml` for that?

Thanks in advance.

#### What command line options do you use?

```
$ dredd 
```

#### What is in your `dredd.yml`?

```yaml
reporter: apiary
custom:
  apiaryApiKey: <apiaryApiKey>
  apiaryApiName: <apiaryApiName>
dry-run: null
hookfiles: null
language: nodejs
sandbox: false
server: null
server-wait: 3
init: false
names: false
only: []
output: []
header: []
sorted: false
user: null
inline-errors: false
details: false
method: []
color: true
level: info
timestamp: false
silent: false
path: []
hooks-worker-timeout: 5000
hooks-worker-connect-timeout: 1500
hooks-worker-connect-retry: 500
hooks-worker-after-connect-wait: 100
hooks-worker-term-timeout: 5000
hooks-worker-term-retry: 500
hooks-worker-handler-host: 127.0.0.1
hooks-worker-handler-port: 61321
config: ./dredd.yml
blueprint: public.apib
endpoint: '<endpoint>'
```

#### What's your `dredd --version` output?

```
dredd v5.1.7 (Darwin 17.5.0; x64)
```

**Comment by honzajavorek** [comment]
You could do this:

```yaml
reporter: [xunit, apiary]
...
output: [./report.xml]
...
```

Does it work for you?
