### ISSUE TITLE
How to share a link to a specific message on a Dredd remote report?

### ISSUE THREAD

**Issue by erajkovic** [apiaryio/dredd#1026]
#### Describe your problem

How can I share a link to a specific message on the Apiary report, once I have uploaded the run?

The link to my collection, which may not work for some:
https://app.apiary.io/ohcapirr/tests/runs

#### What is in your `dredd.yml`?

```yaml - partial
custom:
  apiaryApiKey: xxx
  apiaryApiName: ohcapirr
names: false
only: []
reporter: [apiary]
```

![dredd-missing-link-to-share](https://user-images.githubusercontent.com/4298647/41186111-acaa0dce-6b45-11e8-8470-a1d4993a526c.png)
