### ISSUE TITLE
server executable with spaces cannot be started

### ISSUE THREAD

**Issue by asmodehn** [apiaryio/dredd#1033]
#### Describe your problem

After dredd init, I am trying to launch dredd to test my server.
However dredd complains with : 
```
error: Command to start backend server process failed, exiting Dredd Error: spawn ./build/My ENOENT
    at _errnoException (util.js:992:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:695:11)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3

error Command failed with exit code 1.
```
Removing the spaces around the filename is enough to make it work (see the configuration under)

#### What command line options do you use?

```
$ dredd docs/API.md http://127.0.0.1:3000
```

#### What is in your `dredd.yml`?

```yaml
dry-run: null
hookfiles: null
sandbox: false
server: './build/My Very Long Spaced File Name'
server-wait: 10
init: false
custom: {}
names: false
only: []
reporter: []
output: []
header: []
sorted: false
user: null
inline-errors: false
details: false
method: []
color: true
level: info
timestamp: false
silent: false
path: []
config: ./dredd.yml
blueprint: docs
endpoint: 'http://127.0.0.1:3000'
```

#### What's your `dredd --version` output?

```
dredd v5.1.10 (Linux 4.4.0-128-generic; x64)
```

#### Does `dredd --level=debug` uncover something?

```
verbose: Backend server process specified, starting backend server and then testing
verbose: Using './build/My' as a server command, ["Very","Long","Spaced","File","Name"] as arguments
```

#### Can you send us failing test in a Pull Request?

Not sure how to test this... or how it should be fixed.
Maybe testing for file with space in the name could help ?

I am having this issue using a C++ server that has spaces in name after build

**Comment by honzajavorek** [comment]
Thank you for filing this! The code responsible for this part is [here](https://github.com/apiaryio/dredd/blob/722ddf832441363f6cf49de060c8a1924d8d148a/src/dredd-command.js#L228). The issue is that

```
./build/My Very Long Spaced File Name
```

is not recognizable from e.g.

```
node ./build/server.js 5000
```

so [spawn-args](https://github.com/binocarlos/spawn-args) parses it as a command `./build/My` and its arguments. I believe there is no automatic solution to your problem. You need to give `spawn-args` a clue on how to parse the input, the same way you would need to do on command line.

Does

```yaml
dry-run: null
hookfiles: null
sandbox: false
server: '"./build/My Very Long Spaced File Name"'
server-wait: 10
init: false
...
```

work for you?
