### ISSUE TITLE
How can I set a custom User-Agent for Dredd?

### ISSUE THREAD

**Issue by KonstantinxVx** [apiaryio/dredd#1073]
#### Describe your problem

Hello,

I see that Dredd executes my tests using `User-Agent: Dredd/5.1.7 (Darwin 17.6.0; x64)` and because of this my tests fail.
Is it possible to set my own `User-Agent` in `dredd.yml` ?
#### What command line options do you use?

```
$ dredd
```

#### What is in your `dredd.yml`?

```yaml
reporter: [xunit, apiary]
custom:
  apiaryApiKey: my-key
  apiaryApiName: my-api
dry-run: null
hookfiles: null
language: nodejs
sandbox: false
server: null
server-wait: 3
init: false
names: false
only: []
output: [./report.xml]
header: []
sorted: false
user: null
inline-errors: false
details: false
method: []
color: true
level: info
timestamp: false
silent: false
path: []
hooks-worker-timeout: 5000
hooks-worker-connect-timeout: 1500
hooks-worker-connect-retry: 500
hooks-worker-after-connect-wait: 100
hooks-worker-term-timeout: 5000
hooks-worker-term-retry: 500
hooks-worker-handler-host: 127.0.0.1
hooks-worker-handler-port: 61321
config: ./dredd.yml
blueprint: public.apib
endpoint: 'https://my.endpoint'
```

#### What's your `dredd --version` output?

```
dredd v5.1.7
```
