### ISSUE TITLE
Dredd reporter should be clearer on difference in response bodies

### ISSUE THREAD

**Issue by kylef** [apiaryio/dredd#1104]
Given the following Dredd output, it is telling me that my "plain text" response doesn't match. The problem here is that visually they are pretty identical, I think the only difference is newline perhaps. I think Dredd can do a better job and perhaps actually show a diff between the two so the difference is clearer.

#### Actual Output

```
fail: POST (200) /composer duration: 16ms
fail: body: Real and expected data does not match.

request:
method: POST
uri: /composer
headers:
    Content-Type: application/vnd.refract.parse-result+json; version=1.0
    User-Agent: Dredd/5.1.11 (Darwin 17.7.0; x64)
    Content-Length: 2941

body:
{ /* redacted for brevity */ }


expected:
headers:
    Content-Type: text/vnd.apiblueprint

body:
FORMAT: 1A

# Hello API

## Group

### /message

#### GET

+ Response 200 (text/plain)

        Hello World!

statusCode: 200


actual:
statusCode: 200
headers:
    content-type: text/vnd.apiblueprint
    access-control-allow-origin: *
    content-encoding: identity
    date: Fri, 17 Aug 2018 15:45:19 GMT
    connection: close
    transfer-encoding: chunked

body:
FORMAT: 1A

# Hello API

## Group

### /message

#### GET

+ Response 200 (text/plain)

        Hello World!
```

#### Expected Output

This perhaps isn't correct, just for example, if the problem was about new line a diff like the following:

```diff
  + Response 200 (text/plain)

          Hello World!
+
```
