### ISSUE TITLE
[JSON-schema validation] Unable to generate schema if a parameter in the JSON is named "Pattern"

### ISSUE THREAD

**Issue by CsabaF** [apiaryio/dredd#1108]
#### Describe your problem
Having a parameter with the name `pattern` in my schema will cause a `warn: Parser warning in file './swagger-bundle.yml': Unable to generate application/json example message body out of JSON Schema on line xx` warning and the schema is not validated when the test runs.

My guess is that it is a reserved keyword and it conflicts, since the warning does not show if I rename **pattern** parameter to something else ex **apattern**.

#### What command line options do you use?

```
dredd ./swagger-bundle.yml $HOST_SERVER --hookfiles="./hooks/*.js" --user $DREDD_CREDENTIALS
```

#### What is in your `dredd.yml`?
This is a simplified version of my schema.
```yaml
CommonMetadataFieldPropertiesDtoV1:
  type: object
  properties:
    id:
      type: string
      description: The Id of the metadata field.
    label:
      type: string
      description: The metadata field label.
    type:
      type: string
      description: The metadata field type.
      example: date
    readOnly:
      type: boolean
      description: Flag denoting if this field is read only.
    required:
      type: boolean
      description: Flag denoting if this field is required.
    pattern:
      type: string
      example: "yyyy-MM-dd'T'HH:mm:ssX"
    collection:
      type: object
      description: A (key, MapItem) map. `default`is an example key.
      additionalProperties:
        type: string
    collectionId:
      type: string
    inheritSeriesId:
      type: string

```

#### What's your `dredd --version` output?

```
dredd v5.1.11 (Darwin 17.7.0; x64)
```

#### Does `dredd --level=debug` uncover something?

No info about this except the `warn: Parser warning in file './swagger-bundle.yml': Unable to generate application/json example message body out of JSON Schema on line` warning.
