### ISSUE TITLE
Enum for array cause warning "No enum match for"

### ISSUE THREAD

**Issue by lenertovalucie** [apiaryio/dredd#1114]
#### Describe your problem

Real response looks like this (**with warning: At '/products/0/status' No enum match for: ["Success","ReducedCount"]**)

```
body:
{
  "shopCartId": "qb03sa6g8x",
  "status": "Warning",
  "products": [
    {
      "status": [ 
        "Success",
        "ReducedCount"
      ],
      "id": 60089,
      "count": 0,
      "isUpselling": true,
      "comparisonPrice": true
    }
  ]
}
```

Definition in api-description.yml looks like this:

```
  AddToCart:
    properties:
      products:
        items:
          $ref: '#/definitions/SaveProduct'
        type: array
      shopCartId:
        type: string
      status:
        enum:
        - Success
        - Error
        readOnly: true
        type: string
    type: object
  SaveProduct:
    properties:
      comparisonPrice:
        type: boolean
      count:
        format: int32
        type: integer
      id:
        format: int32
        type: integer
      isUpselling:
        type: boolean
      status:
        enum:
          - Success
          - ReducedCount
          - Error
        type: array
        items:
          type: string
    type: object
```

'/products/0/status' is type of array, so the response should be correct. Is there something I did not notice?

#### What command line options do you use?

```
$ dredd 
```

#### What is in your `dredd.yml`?

```yaml
dry-run: null
hookfiles: ../hooks.py
language: python
sandbox: false
server:
server-wait: 3
init: false
custom:{}
names: false
only: []
reporter: apiary
output: []
header: []
sorted: false
user: null
inline-errors: false
details: false
method: []
color: true
level: info
timestamp: false
silent: false
path: []
hooks-worker-timeout: 5000
hooks-worker-connect-timeout: 15000
hooks-worker-connect-retry: 5000
hooks-worker-after-connect-wait: 100
hooks-worker-term-timeout: 5000
hooks-worker-term-retry: 500
hooks-worker-handler-host: 127.0.0.1
hooks-worker-handler-port: 61321
config: ./dredd.yml
blueprint: api-description.yml
endpoint: 'http://...'

```

#### What's your `dredd --version` output?

```
dredd v5.1.11 (Windows_NT 10.0.16299; x64)
```

#### Does `dredd --level=debug` uncover something?

no

#### Can you send us failing test in a Pull Request?

no

**Comment by kylef** [comment]
Sure, status is of type array, but there is an enumeration which takes presidence. The enumeration says that the value for status can be either "Success" "ReducedCount" or "Error".

```yaml
status:
  enum:
    - Success
    - ReducedCount
    - Error
  type: array
  items:
    type: string
```

I expect you instead want to do something like:

```yaml
status:
  type: array
  items:
    enum:
      - Success
      - ReducedCount
      - Error
```

Where you define an array which can contain the enumeration values.
