### ISSUE TITLE
Can not overlap content-type

### ISSUE THREAD

**Issue by kvokka** [apiaryio/dredd#1146]
**Describe the bug**

Given:
```
swagger: '2.0'
info:
  version: '0.1.0'
basePath: /api/v1
host: 'localhost:5000'
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json; charset=utf-8

paths:
  /foos/{id}/:
    delete:
      description: 'foo'
      parameters:
        - name: "id"
          in: "path"
          description: "ID of foo"
          required: true
          type: integer
          enum:
          - 42
      responses:
        204:
          description: "OK"
```

Produce output:
```
expected:
headers:
    Content-Type: application/json; charset=utf-8

statusCode: 204


actual:
statusCode: 204
headers:
    cache-control: no-cache
    x-request-id: 03565c02-cdfd-49b9-af36-506cae55cb8a
    x-runtime: 0.841603
    connection: close
```

And i can not overlap it in the specification

**Expected behavior**
add the ability to add option to describe this in `yaml` files

**What's your `dredd --version` output?**

```
5.2.0
```

PS: I found the solution (and it works) to hack it, but i'm not sure, that it is semantically  right:

```
before "/api/v1/foos/{id}/ > Delete the foo > 204 > application/json; charset=utf-8" do |transaction|
  create :foo, id: 42
  transaction.fetch("expected", {}).fetch("headers", {}).delete("Content-Type")
end

```

**Comment by honzajavorek** [comment]
Hi @kvokka, I'm sorry, I must have missed this issue.

Do I understand correctly that you're trying to test 204 No Content response in a document where everything produces JSON by default, and Dredd considers this to be a problem, because the 204 No Content response should not have a Content-Type?

While this seems to be correct rigorously, I can see it can be annoying from user's perspective. @apiaryio/adt Do you think it would be a good idea to suppress Content-Type for 204 and 205 responses in the Swagger adapter?

**Comment by kvokka** [comment]
Hi @honzajavorek , than you for your responce!

Yes, you understood me right.

In this period I found one more, even more pretty solution
```
delete:
  tags:
    - Users
  description: User logout
  produces:
    - "text/plain"
```

And this construction allow to avoid this situation too. But, maybe it can be good idea to omit context-type check, if the body is empty?

**Comment by honzajavorek** [comment]
You are right, this is nicer solution. Maybe even this could work (did not try)?

```yaml
delete:
  tags:
    - Users
  description: User logout
  produces:
    - ""
```

I agree that it would be convenient to omit the content-type, but at the same time, the document should be universal and describe the API as it is, in the most real way. The semantics of OpenAPI 2 unfortunately lead to this, but omitting the content-type in the Swagger adapter or in Dredd means the API stays described with the problem in place for other Swagger tools you may use or integrate with.

In other words, if you have produces with JSON and 204 No Content response, other tools will/should still translate it to a response with a JSON content type and that's not how the API truly behaves, and Dredd wouldn't be able to warn you about it.

So at the end, I tend to think we should not introduce any specific behavior in this regard. Opinions?
