### ISSUE TITLE
x-unit-reporter.js does not adhere to JUnit schema

### ISSUE THREAD

**Issue by timbeynart-nbcuni** [apiaryio/dredd#1152]
**Describe the bug**
Jenkins JUnit plugin throws error when reading XML report generated by Dredd. 
This is because the generated report does not follow the schema defined by JUnit.
The following is logged when reading an report using Jenkins JUnit plugin:
```
INFO: [JUnit] - 1 test report file(s) were found with the pattern 'dreddReport.xml' relative to '/home/ec2-user/workspace/project-name' for the testing framework 'JUnit'.
WARNING: The file '/home/ec2-user/workspace/project-name/dreddReport.xml' is an invalid file.
WARNING: At line 2 of file:/home/ec2-user/workspace/project-name/dreddReport.xml:cvc-complex-type.3.2.2: Attribute 'skip' is not allowed to appear in element 'testsuite'.
FATAL: The result file '/home/ec2-user/workspace/project-name/dreddReport.xml' for the metric 'JUnit' is not valid. The result file has been skipped.
```
This is due to the `skip` attribute in the `testsuite` element in the XML report. For example:
```
<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="Dredd Tests" tests="67" failures="1" errors="0" skip="3" timestamp="Tue, 11 Dec 2018 02:17:50 GMT" time="2.934">
<testcase name="POST (200) /app/endpoint" time="NaN"><skipped/></testcase>
<testcase name="POST (401) /app/endpoint" time="NaN"><skipped/></testcase>
<testcase name="POST (200) /app/endpoint" time="1.406"><failure><![CDATA[Message: ...]]></failure></testcase>
<testcase name="POST (401) /app/endpoint" time="NaN"><skipped/></testcase>
</testsuite>
```
In order for the plugin to parse the XML successfully, `skip="3"` should be `skipped="3"`.  
The best resource for the JUnit schema is actually in the source code:
http://svn.apache.org/repos/asf/ant/core/trunk/src/main/org/apache/tools/ant/taskdefs/optional/junit/XMLConstants.java  

I can resolve this issue by modifying https://github.com/apiaryio/dredd/blob/master/src/reporters/x-unit-reporter.js. I'll add a PR to this ticket ASAP.

**To Reproduce**
Steps to reproduce the behavior. How do you call the dredd command? Which command line options?
To reproduce, run a Dredd test with at least one test skipped.   
`dredd --level=debug --reporter junit --output dreddReport.xml`  
**Expected behavior**
Generated XML should match JUnit spec:
```
<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="Dredd Tests" tests="67" failures="1" errors="0" skipped="3" timestamp="Tue, 11 Dec 2018 02:17:50 GMT" time="2.934">
<testcase name="POST (200) /app/endpoint" time="NaN"><skipped/></testcase>
<testcase name="POST (401) /app/endpoint" time="NaN"><skipped/></testcase>
<testcase name="POST (200) /app/endpoint" time="1.406"><failure><![CDATA[Message: ...]]></failure></testcase>
<testcase name="POST (401) /app/endpoint" time="NaN"><skipped/></testcase>
</testsuite>
```

**What is in your `dredd.yml`?**
This is fake, but adding only 1 test to the yaml will cause the rest to be skipped.
```yaml
dry-run: null
hookfiles: 'dredd-hooks.js'
language: nodejs
sandbox: false
server: sls offline start --environment devwest
server-wait: 3
init: false
custom: {}
names: false
only: [
    'application > fake > GET > 200'
]
reporter: []
output: []
header: []
sorted: false
user: null
inline-errors: false
details: false
method: []
color: true
level: info
timestamp: false
silent: false
path: []
hooks-worker-timeout: 5000
hooks-worker-connect-timeout: 1500
hooks-worker-connect-retry: 500
hooks-worker-after-connect-wait: 100
hooks-worker-term-timeout: 5000
hooks-worker-term-retry: 500
hooks-worker-handler-host: localhost
hooks-worker-handler-port: 61321
config: ./dredd.yml
blueprint: swagger.yaml
endpoint: 'http://localhost:3000'
```

**What's your `dredd --version` output?**

```
dredd v5.2.0 (Darwin 16.7.0; x64)  
```

**Does `dredd --level=debug` uncover something?**
If you run Dredd with debugging output, do you see any interesting information relevant to the bug?
No.

**Can you send us failing test in a Pull Request?**
I can put together a simple project to reproduce. I'm trying to figure out a way to demo this outside of Jenkins.
