### ISSUE TITLE
`format: uuid` cause fail

### ISSUE THREAD

**Issue by utisam** [apiaryio/dredd#1218]
**Describe the bug**

`format: uuid` of JSON schema cause fail.

```
fail: body: The id property must be an uuid (current value is "fdb4bbc7-ab05-4269-bdb7-d464f28a959f").
```

**To Reproduce**

```
swagger: "2.0"
info:
  title: UUID format cause fail
  description: Test
  version: 1.0.0
basePath: /
paths:
  /test.json:
    get:
      summary: Test
      responses:
         200:
            description: OK
            schema:
              type: object
              properties:
                id:
                  type: string
                  format: uuid
```

And response `test.json` by `python3 -m http.server`.

```
{
    "id": "fdb4bbc7-ab05-4269-bdb7-d464f28a959f"
}
```

```
npx dredd
```

**Expected behavior**

Validate string as an UUID or ignore as an unsupported format.
It makes inconvenient to use with other tools.

**What is in your `dredd.yml`?**

```yaml
init: true
dry-run: null
hookfiles: hooks.js
language: nodejs
require: null
server: python3 -m http.server
server-wait: 3
custom: {}
names: false
only: []
reporter: []
output: []
header: []
sorted: false
user: null
inline-errors: false
details: false
method: []
color: true
level: info
timestamp: false
silent: false
path: []
hooks-worker-timeout: 5000
hooks-worker-connect-timeout: 1500
hooks-worker-connect-retry: 500
hooks-worker-after-connect-wait: 100
hooks-worker-term-timeout: 5000
hooks-worker-term-retry: 500
hooks-worker-handler-host: 127.0.0.1
hooks-worker-handler-port: 61321
config: ./dredd.yml
blueprint: ./example-api.yml
endpoint: 'http://localhost:8000/'
```

**What's your `dredd --version` output?**

```
dredd v7.1.0 (Linux 4.19.10-300.fc29.x86_64; x64)
```
