### ISSUE TITLE
Case sensitive header lines

### ISSUE THREAD

**Issue by ghost** [apiaryio/dredd#122]
For example: 

    Content-Type: application/json

does not match

    content-type: application/json

**Comment by JackuB** [comment]
Bump
To elaborate:

I'm setting 

```apib
### Exchange credentials for token [POST]
+ Request (application/json; charset=utf-8)
    + Headers

            Authorization: Basic ABCDEF
```

and then in my hook I have:

```js
transaction.request.headers.authorization = header;
```

which results in:

```
headers:
    Content-Type: application/json; charset=utf-8
    Authorization: Basic ABCDEF
    User-Agent: Dredd/1.0.6 (Darwin 15.3.0; x64)
    authorization: Some other header
    Content-Length: 42
```

[RFC2616 specifies that header names should be case-insensitive](http://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.2)

> Each header field consists of a name followed by a colon (":") and the field value. Field names are case-insensitive.
