### ISSUE TITLE
OpenAPI v3 parameter in header is unsupported

### ISSUE THREAD

**Issue by y-luis** [apiaryio/dredd#1287]
**Describe the bug**
Although [parameter in header is supported](https://github.com/apiaryio/api-elements.js/blob/master/packages/fury-adapter-oas3-parser/STATUS.md), a warning shows the opposite: `warn: Parser warning in 'docs/user/configuration/openapi.yaml': 'Parameter Object' 'in' 'header' is unsupported on line X` and no header is added to the request:

```request:
method: PUT
uri: /queues
headers:
    Content-Type: application/json
    User-Agent: Dredd/8.0.5 (Linux 3.10.0-957.5.1.el7.x86_64; x64)

body:
...
```

**To Reproduce**
Run `dredd` with the following OpenAPI v3 specification (fragment):

```
paths:
  /queues:
    put:
      description: Updates specific Queues settings or creates them (in case those don't exist)
      tags:
        - Queues
      operationId: putQueues
      parameters:
        - in: header
          name: If-Match
          description: Resource ETag value
          required: true
          schema:
            type: string
          example: 'aee1d1a225d0f7476bf0100a87298664'
```

**Expected behavior**
No warning regarding parameter in header and header present in the request.

**What is in your `dredd.yml`?**

```yaml
color: true
dry-run: null
hookfiles: "hooks.js"
language: nodejs
require: null
server: null
server-wait: 3
init: false
custom: {}
names: false
only: []
reporter: []
output: []
header: []
sorted: true
user: null
inline-errors: false
details: false
method: []
loglevel: warning
path: []
hooks-worker-timeout: 5000
hooks-worker-connect-timeout: 1500
hooks-worker-connect-retry: 500
hooks-worker-after-connect-wait: 100
hooks-worker-term-timeout: 5000
hooks-worker-term-retry: 500
hooks-worker-handler-host: 127.0.0.1
hooks-worker-handler-port: 61321
config: ./dredd.yml
blueprint: docs/user/configuration/openapi.yaml
endpoint: "http://10.22.22.20:9000"
```

**What's your `dredd --version` output?**

```
dredd v8.0.5 (Linux 3.10.0-957.5.1.el7.x86_64; x64)
```

**Does `dredd --loglevel=debug` uncover something?**
No

**Can you send us failing test in a Pull Request?**
Yes.
