### ISSUE TITLE
Dredd emitted errors do not contain source maps

### ISSUE THREAD

**Issue by kylef** [apiaryio/dredd#1306]
When Dredd fails due to missing parameter default, example etc values it produces an error without a source map which means the user is forced to decipher where the they can add the field in their API Description Document. 

For example:

> error: Compilation error in '/Users/kyle/Projects/apiaryio/api-elements.js/dredd-1286.json': Required URI parameter 'accountName' has no example or default value. (x > /login > POST)

With OAS 3 this could be traversing a large file, and then following references to where the parameter is defined. The parser can emit source maps for this (with requested with generateSourceMap option). The href varialbe "key" inside hrefVariables contains a source map which can help identify where the problem lies:

```
                      "content": {
                        "key": {
                          "element": "string",
                          "attributes": {
                            "sourceMap": {
                              "element": "array",
                              "content": [
                                {
                                  "element": "sourceMap",
                                  "content": [
                                    {
                                      "element": "array",
                                      "content": [
                                        {
                                          "element": "number",
                                          "content": 515
                                        },
                                        {
                                          "element": "number",
                                          "content": 13
                                        }
                                      ]
                                    }
                                  ]
                                }
                              ]
                            }
                          },
                          "content": "parameter name"
                        }
                      }
```

**Comment by honzajavorek** [comment]
Yes, that's a flaw of current implementation. I can improve it now when I'm digging into it. One thing to consider is that currently Dredd only needs source maps of the annotations, which now have line/coulmn numbers. Those are not present in the source maps to `hrefVariables`, if I'm correct, so using those would mean that either Dredd cannot drop the logic to calculate the line/column, or API Elements need to provide the line/column for that element.

**Comment by kylef** [comment]
Yes, we've thought about line/column on other elements and we've avoided it for now because of the potential of significantly increasing the parse result size causing performance problems/high-memory use. We hadn't analysed the full impact at the moment (we have no demand for it yet). Potentially most of the time you don't want line/column numbers unless you are informing the user about somethin related, so perhaps they are better to be calculated after the fact when rendering the errors (API Elements should provide an API to do this).

We will need to think about this in the future and we can work on it when needed. Perhaps the parser (and subsequently the API Elements Web API) could have some way to define "filters" so you can declare where you want source maps, currently is is "boolean", "yes I want them" or "no I do not want them" where they are always there for annotations. May be nicer to be able to specify "I want them for hrefVariables" and "annotations" etc.

Parser implementations differ, in OAS 3 we always have line/column internally (and source maps on entire tree) and then we filter them out of the result. The underlying YAML parser always emits line/column. I believe line/column in Drafter is computed after the fact.

**Comment by honzajavorek** [comment]
Would it make sense for minim to calculate it on demand somehow if it's not there already? That could provide a uniform interface for the tools building on top of API Elements.

**Comment by kylef** [comment]
One step further, it would be great to be able to know which line a message body was defined on which does not match the APIs result, this can be hard to discover on a larger API with API description document which has many example request/response.

Example:

```
request:
method: POST
uri: /parser
headers:
    Content-Type: text/vnd.apiblueprint
    Accept: application/vnd.refract.parse-result+yaml; version=1.0
    User-Agent: Dredd/9.0.0 (Darwin 18.2.0; x64)

body:
# Hello API
## /message
### GET
+ Response 200 (text/plain)

        Hello World!



expected:
headers:
    Content-Type: application/vnd.refract.parse-result+yaml; version=1.0

body:
element: parseResult
content:
  ...

statusCode: 200


actual:
statusCode: 200
headers:
    content-type: application/vnd.refract.parse-result+yaml; version=1.0
    access-control-allow-origin: *
    content-encoding: identity
    date: Tue, 09 Apr 2019 20:55:02 GMT
    connection: close
    transfer-encoding: chunked

bodyEncoding: utf-8
body:
element: parseResult
content:
  ...
```

Information about where a header, body etc is defined is needed.
