### ISSUE TITLE
apiaryApiKey & apiaryApiName are no longer working from dredd.yml config

### ISSUE THREAD

**Issue by skazancev** [apiaryio/dredd#1377]
**Describe the bug**
apiaryApiKey & apiaryApiName are no longer working from dredd.yml config since 10.0.0

**To Reproduce**
1) dredd init
    - added apiary key
    - added apiary name
2) write simple apiary.apib
3) dredd
4) now i can see the following message:

```
warn: 
Apiary API Key or API Project Subdomain were not provided.
Configure Dredd to be able to save test reports alongside your Apiary API project:
https://dredd.org/en/latest/how-to-guides/#using-apiary-reporter-and-apiary-tests
```

**Expected behavior**
It should use apiaryApiKey & apiaryApiName variables

**What is in your `dredd.yml`?**

```yaml
color: true
dry-run: null
hookfiles: null
language: nodejs
require: null
server: python manage.py runserver
server-wait: 3
init: false
custom:
  apiaryApiKey: my-api-key
  apiaryApiName: my-api-name
names: false
only: []
reporter: apiary
output: []
header: []
sorted: false
user: null
inline-errors: false
details: false
method: []
loglevel: warning
path: []
hooks-worker-timeout: 5000
hooks-worker-connect-timeout: 1500
hooks-worker-connect-retry: 500
hooks-worker-after-connect-wait: 100
hooks-worker-term-timeout: 5000
hooks-worker-term-retry: 500
hooks-worker-handler-host: 127.0.0.1
hooks-worker-handler-port: 61321
config: ./dredd.yml
blueprint: apiary.apib
endpoint: 'http://127.0.0.1:3000'
```

**What's your `dredd --version` output?**

```
dredd v11.1.4 (Darwin 18.6.0; x64)
```

**Does `dredd --loglevel=debug` uncover something?**

> If you run Dredd with debugging output, do you see any interesting information relevant to the bug?

 - No
