### ISSUE TITLE
Dredd ignores 'application/json; charset=utf-8' in OAS3 

### ISSUE THREAD

**Issue by tishibas** [apiaryio/dredd#1391]
**Describe the bug**
I try to use Dredd with OpenAPI3. I found that Dredd ignores the tests when the key of MediaObject is `application/json; charset=utf-8`.
When it is `application/json`, Dredd does not ignored the tests.

**To Reproduce**
```
openapi: 3.0.0
info:
  version: "0.0.1"
  title:  API
  description: 'TODO: Add a description'
paths:
  /test:
    get:
      responses:
        "200":
          description: test
          content:
            application/json; charset=utf-8:
              schema:
                type: object
                properties:
                  foo:
                    type: string
```

**Expected behavior**

**What is in your `dredd.yml`?**

```yaml
dry-run: null
hookfiles: './build/darwin_amd64/hooks'
language: './build/bin/darwin_amd64/goodman'
server: ''
server-wait: 10
init: false
custom: {}
names: false
only: []
reporter: []
output: []
header: []
sorted: false
user: null
inline-errors: false
details: false
method: []
color: true
loglevel: warning
path: []
hooks-worker-timeout: 60000
hooks-worker-connect-timeout: 60000
hooks-worker-connect-retry: 1000
hooks-worker-after-connect-wait: 100
hooks-worker-term-timeout: 5000
hooks-worker-term-retry: 500
hooks-worker-handler-host: 127.0.0.1
hooks-worker-handler-port: 61321
blueprint: './api-spec-oas3.yml'
endpoint: 'http://127.0.0.1:8888'
```

**What's your `dredd --version` output?**

```
dredd v11.2.3 (Darwin 18.6.0; x64)
```
