### ISSUE TITLE
Ability to negate server option

### ISSUE THREAD

**Issue by kylef** [apiaryio/dredd#1466]
When I have a configuration file, such as:

```yml
language: nodejs
hookfiles: dredd/*.js
server: env VAULT_ENABLED=0 node functions/transform/lib/http.js
server-wait: 3
color: true
path: []
blueprint: 'apiary.apib'
endpoint: 'http://localhost:8000'
```

I'd like to be able to override the server, to not run, for example if I am running the script against the already ran server in some kind of debug mode, or docker image etc.

Having an argument such as `--no-server` which negates the server option would be neat.

**Workaround**

```
$ npx dredd --config dredd.local.yml --server '/usr/bin/true'
```

Although, this suffers from slowing down the tests as there is 3 second wait due to `server-wait`.

**Describe the solution you'd like**

I'd like to see `--no-server` (or something similiar, `--no` is common pattern for disabling boolean flags in a lot of tools I use so this feels like an intuitive option, although never seen pattern where main argument requires option (i.e, `git --no-pager`).

https://github.com/kylef/swiftenv/blob/2caa152249c02af42360afd737c9b7ae679d2910/libexec/swiftenv-install#L263-L266
