### ISSUE TITLE
additionalProperties and required fields ignored when using a schema described with allOf

### ISSUE THREAD

**Issue by gac3k** [apiaryio/dredd#1647]
**Describe the bug**
A similar problem has already been reported here in past, and was related to fact, that when Swagger 2 schema is not de-referenced, the more strict validation (`additionalProperties` and `required` properties, are not being validated). That can be solved by well... de-referencing the schema. But then, there is another problem. De-referencing is not merging the `allOf` references (which is an expected behavior) and it seems that Dredd can't handle such behavior properly. Meaning it can interpret the schema and execute the request, but `additionalProperties` and `required` part of schema seems to be ignored completely.

**To Reproduce**
1. Create a de-referenced schema containing `allOf` parts
2. Run dredd tests against that schema

**Expected behavior**
`additionalProperties` and `require` flags should be considered during test.

**What is in your `dredd.yml`?**

```yaml
color: true
dry-run: false
hookfiles: 'test/hooks.js'
language: nodejs
require: null
server: 'npm start'
server-wait: 3
init: false
custom: {}
names: false
only: []
reporter: html
output: []
header: []
sorted: false
user: null
inline-errors: true
details: true
method: []
loglevel: error
path: []
hooks-worker-timeout: 5000
hooks-worker-connect-timeout: 1500
hooks-worker-connect-retry: 500
hooks-worker-after-connect-wait: 100
hooks-worker-term-timeout: 5000
hooks-worker-term-retry: 500
hooks-worker-handler-host: 127.0.0.1
hooks-worker-handler-port: 61321
config: ./dredd.yml
blueprint: docs/swagger2.yml
endpoint: 'http://localhost:61355'
```

**What's your `dredd --version` output?**

```
dredd v12.2.0 (Linux 5.0.0-37-generic; x64)
```
