### ISSUE TITLE
hookfiles issue for hook files not in the same directory

### ISSUE THREAD

**Issue by AlexDalusongiQ** [apiaryio/dredd#1657]
**Describe the bug**
When using a hookfile that is not in the same directory as the dredd.yml, it looks like dredd is just not able to find the file

**To Reproduce**

1. Open cmd
2. Navigate to the directory where the dredd.yml exists
3. Type `dredd` and hit ENTER

**Expected behavior**
Since the file path is defined properly for the hookfile (blueprint uses the same syntax), dredd should be able to find and use the hookfile in a different directory.

If I input a wrong file name, an error that says `Could not find any files on path` is thrown. However when I input the correct file path (relative or absolute), it looks like the hookfile that is not in the same directory is not being run.

**What is in your `dredd.yml`?**

```
color: true
reporter: ['apiary', 'markdown', 'nyan', 'html']
custom:
  apiaryApiKey: *
  apiaryApiName: *
dry-run: null
hookfiles: 
  - ../base-hook.js
  #- hooks.js <-this one works
language: nodejs
require: null
server: npm start
server-wait: 3
init: false
names: false
only: "/Companies({CompanyId})/CatalogItems > Get Availability for All Catalog Items > 200 > application/json"
output: []
header: []
sorted: false
user: null
inline-errors: false
details: false
method: GET
loglevel: error
path: []
hooks-worker-timeout: 5000
hooks-worker-connect-timeout: 1500
hooks-worker-connect-retry: 500
hooks-worker-after-connect-wait: 100
hooks-worker-term-timeout: 5000
hooks-worker-term-retry: 500
hooks-worker-handler-host: 127.0.0.1
hooks-worker-handler-port: 61321
config: ./dredd.yml
blueprint: ../../swagger/inventory-availability.yaml
endpoint: https://availabilityrc.iqmetrix.net/v1

```

**What's your `dredd --version` output?**

```
dredd v12.2.0 (Windows_NT 10.0.18362; x64)
```

**Does `dredd --loglevel=debug` uncover something?**
It does not.

**Can you send us failing test in a Pull Request?**
I'm not sure how to do this.
