### ISSUE TITLE
When using OpenAPI3.0 Json file, header will not be detected in schema object

### ISSUE THREAD

**Issue by abnernat** [apiaryio/dredd#1785]
**Describe the bug**
When using OpenAPI3.0 Json file, header will not be detected in schema object

**To Reproduce**
Steps to reproduce the behavior. How do you call the dredd command? Which command line options?
Write header parameter like:
```
{
            "name": "token",
            "in": "header",
            "required": true,
            "schema": { "type": "string", "example": "395802952"}
}
```

**Expected behavior**
In Open API standard, example in header object normally stays in schema object, but dredd can't resolve the document when example is not in the top level of parameter object.
**What is in your `dredd.yml`?**

```yaml
( paste your dredd.yml contents here )
color: true
dry-run: true
hookfiles: hook.js
language: nodejs
require: null
server: 
server-wait: 10
init: false
custom:
  apiaryApiKey: 430ec244c9b9f698c8cdb5aeba4f7dde
  apiaryApiName: abnernat
names: false
only: []
reporter: apiary
output: []
header: []
sorted: false
user: null
inline-errors: false
details: false
method: []
loglevel: debug
path: []
hooks-worker-timeout: 5000
hooks-worker-connect-timeout: 1500
hooks-worker-connect-retry: 500
hooks-worker-after-connect-wait: 100
hooks-worker-term-timeout: 5000
hooks-worker-term-retry: 500
hooks-worker-handler-host: 127.0.0.1
hooks-worker-handler-port: 61321
config: ./dredd.yml
blueprint: './test.json'
endpoint: 'http://127.0.0.1:3000/'
```

**What's your `dredd --version` output?**

```
( paste your output here )
dredd v13.1.2 (Darwin 19.5.0; x64)
```

**Does `dredd --loglevel=debug` uncover something?**
If you run Dredd with debugging output, do you see any interesting information relevant to the bug?

This is the only error message related to this problem. It caused by the missing of example property.
```
2020-06-30T12:37:03.004Z - error: Unable to compile HTTP transactions from API description document '/Users/abnernat/Project/on-going/yuhu/around7-background/test.json': Cannot read property 'toValue' of undefined: Cannot read property 'toValue' of undefined
```

**Can you send us failing test in a Pull Request?**
We'll gladly help you to contribute; answering yes raises the chances the issue gets fixed.

I don't know how, if you tells me how to do it I will.
