### ISSUE TITLE
When trying to handle multipart/form-data with binary content using Dredd PHP Hooks getting an error: "Unexpected end of JSON input"

### ISSUE THREAD

**Issue by VsevolodLoboda** [apiaryio/dredd#1794]
**Describe the bug**
I use Dredd PHP Hooks to pre-process each transaction. I have an API method for uploading images, and before testing it I replace the body transaction with a valid multipart/form-data request like following:

```
--BOUNDARY
Content-Disposition: file; name="photo"
Content-type: image/png
Content-Transfer-Encoding: base64

{image binary content here}
--BOUNDARY--
```

After running the tests, I get the following error:

```
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Socket.handlerClient.on (/var/www/node_modules/dredd/build/HooksWorkerClient.js:286:44)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
```

It works if I preliminarily encode binary content in base64, for example, but this option does not suit me.

**Expected behavior**
The request is successfully sent to the server with binary content in the body

**What is in your `dredd.yml`?**

```yaml
dry-run: null
hookfiles: tests/Dredd/v1/hookfile.v1.php
language: vendor/bin/dredd-hooks-php
require: null
server: null
server-wait: 3
init: false
custom: {}
names: false
only: []
reporter: []
output: []
header: []
sorted: false
user: null
inline-errors: false
details: false
method: []
color: true
loglevel: warning
path: []
hooks-worker-timeout: 5000
hooks-worker-connect-timeout: 10000
hooks-worker-connect-retry: 500
hooks-worker-after-connect-wait: 100
hooks-worker-term-timeout: 5000
hooks-worker-term-retry: 500
hooks-worker-handler-host: 127.0.0.1
hooks-worker-handler-port: 61321
config: ./dredd.yml
blueprint: docs/open_api/swagger.json
endpoint: 'http://127.0.0.1:80'
```

**What's your `dredd --version` output?**

```
dredd v13.1.2 (Linux 4.19.76-linuxkit; x64)
```
