### ISSUE TITLE
Example for array as model property not being picked up

### ISSUE THREAD

**Issue by finiteinfinity** [apiaryio/dredd#1796]
**Describe the bug**
When testing with dredd, I have a model where one property is defined as:
```
myArrayProperty:
    type: array
    minItems: 7
    maxItems: 7
    items:
      type: boolean
    example: [true, false, true, false, true, false, true]
```

The tests fail to pick up the data given in `example`, instead passing just
```
"myArrayProperty": [
      false
    ],
```
to the request instead.

**To Reproduce**
Steps to reproduce the behavior. How do you call the dredd command? Which command line options?
Define a model with an array property with a minimum length > 1 and give a suitable example (see above). Run tests and observe example given being skipped over

**Expected behavior**
Dredd picks up the provided example and passes it through to the request

**What is in your `dredd.yml`?**

Not relevant to issue

**What's your `dredd --version` output?**
```
dredd v11.2.9 (Darwin 19.5.0; x64)
```

**Does `dredd --loglevel=debug` uncover something?**
If you run Dredd with debugging output, do you see any interesting information relevant to the bug?
No

**Can you send us failing test in a Pull Request?**
N/A
