### ISSUE TITLE
Dredd reporter sends data to apiary reporter if names is true

### ISSUE THREAD

**Issue by abtris** [apiaryio/dredd#193]
Dredd 0.5.2

dredd.yaml
```
reporter: apiary
custom:
  apiaryApiKey: xxxxxxxxxxxxxxxxx
  apiaryApiName: nodeschoolhk
dry-run: null
hookfiles: [koa-dredd-hook.js]
sandbox: false
server: node koa/index.js
server-wait: 3
init: false
names: true
only: []
output: []
header: []
sorted: false
user: null
inline-errors: false
details: false
method: []
color: true
level: info
timestamp: false
silent: false
path: []
blueprint: nodeschoolhk-apiary.apib
endpoint: 'http://localhost:3000'
```
Example is from https://github.com/abtris/nodeschool-hk-2015-05-23

In Apiary, I see empty records of run without any data. I think you can skip reporter if names is true.
