### ISSUE TITLE
Improved documentation for running dredd in CI / docker

### ISSUE THREAD

**Issue by arthurzenika** [apiaryio/dredd#2049]
**Is your feature request related to a problem? Please describe.**

We were trying to get dredd to run in Gitlab-CI with an AutoDevops deployed application, and we thought that we were done by adding : 

```
🧑‍⚖️ dredd_tests:
    stage: performance
    image: 
        name: apiaryio/dredd
        entrypoint: [""]
    script:
        - CI_ENVIRONMENT_URL="$(cat environment_url.txt)"
        - export CI_ENVIRONMENT_URL
        - dredd docs/swagger.json $CI_ENVIRONMENT_URL
```

This seemed to run fine and was green... but... it was only giving warnings about the swagger file and not running any tests. 

We then read the documenation about hooks not running in docker (we have no custom hooks, so we thought it would work).  

**Describe the solution you'd like**

It would be nice to have a more precise documentation about what dredd does or doesn't do when run in docker or in a CI that uses docker (for example CircleCI or travis that is mentionned in the cli and docs?)

**Describe alternatives you've considered**
Including the dummy hooks server in a command line. Or having a --no-hooks or --sync option ? 

Oh, by the way, dredd is awesome on the command line, really useful, thanks!
