### ISSUE TITLE
CLI output doesn't mention which transaction examples when showing failure

### ISSUE THREAD

**Issue by kylef** [apiaryio/dredd#299]
When a blueprint has many transaction examples it's difficult to match the failing ones to the corresponding pairs in your blueprint. This is due to the request title not being shown.

Here's an example transaction example with a title:

```apib
+ Request Parse API Blueprint into Parse Result Namespace returned as JSON (text/vnd.apiblueprint)

    + Headers

            Accept: application/vnd.refract.parse-result+json

    + Body

            # GET /message
            + Response 200 (text/plain)

                    Hello World!

+ Response 200 (application/vnd.refract.parse-result+json)

        { ... }
```

It would be great if the title "Parse API Blueprint into Parse Result Namespace returned as JSON" was shown in the CLI output.

```
request:
body:
< 200
Hello World!

headers:
    Content-Type: text/vnd.legacyblueprint
    Accept: application/vnd.apiblueprint.ast+json
    User-Agent: Dredd/1.0.1 (Darwin 15.0.0; x64)
    Content-Length: 19

uri: /parser
method: POST


expected:
headers:
    Content-Type: application/vnd.error+json

body:
{
    "message": "SyntaxError: Expected \"---\", \"HOST:\" or empty line but \"R\" found."
}

statusCode: 422


actual:
statusCode: 406
headers:
    server: Cowboy
    connection: close
    access-control-allow-credentials: true
    content-type: application/vnd.error+json
    content-length: 218
    etag: W/"da-e0RBUtCy+71LbEusBJrb6Q"
    date: Thu, 03 Dec 2015 11:52:25 GMT
    via: 1.1 vegur

body:
{"statusCode":406,"message":"None of requested Content-Types \"application/vnd.apiblueprint.ast+json\" is supported. Supported MIME types: application/vnd.legacyblueprint.ast, application/vnd.legacyblueprint.ast+json"}



fail: POST /composer duration: 633ms
fail: headers: Header 'content-type' has value 'application/vnd.error+json' instead of 'text/vnd.apiblueprint'
body: Can't validate real media type 'application/vnd.error+json' against expected media type 'text/plain'.
statusCode: Status code is not '200'
```
