### ISSUE TITLE
Dredd init wrong modify .travisci.yml?

### ISSUE THREAD

**Issue by abtris** [apiaryio/dredd#369]
Original `.travisci.yml` file:

```
sudo: false
language: php
cache:
  directories:
    - $HOME/.composer/cache
php:
  - 5.5
before_install:
  - npm install -g dredd
  - composer install
script:
  - dredd
env:
  global:
    - secure: XXXXXXXXX
```

and after `dredd init`:

```
sudo: false
language: php
cache:
  directories:
    - $HOME/.composer/cache
php:
  - 5.5
before_install:
  - npm install -g dredd
  - composer install
script:
  - dredd
env:
  global:
    - secure: XXXXXXXXX
before_script:
  - dredd
```

I think works good before I add `env` section.
