### ISSUE TITLE
 Can't validate real media type 'application/json;charset=utf-8' against expected media type 'text/plain'

### ISSUE THREAD

**Issue by paddingme** [apiaryio/dredd#513]
I tested  the  post request,  but get the following error message,   I try to change  content-type ,also get  the same result.  

```
$ dredd
info: Configuration dredd.yml found, ignoring other arguments.
info: Using apiary reporter.
warn: Apiary reporter environment variable APIARY_API_KEY or APIARY_API_NAME not defined.
info: Beginning Dredd testing...
fail: POST /xspj/api/subject/activity/orgs duration: 276ms
info: Displaying failed tests...
fail: POST /xspj/api/subject/activity/orgs duration: 276ms
fail: body: Can't validate real media type 'application/json;charset=utf-8' against expected media type 'text/plain'.
statusCode: Status code is not '201'

request:
body:

headers:
    Content-Type: application/x-www-form-urlencoded;charset=UTF-8
    Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE0NjUzNjMyNTksImlzcyI6IjBkYzQyM2YyZGYzYjRlNDJiZDI4NzFkZjczMWY2MjdiIn0.DwM2ez07Y5bLfG5ZvYQKSDCJX_jvV_OgrsUxp32uQG4
    User-Agent: Dredd/1.0.11 (Darwin 15.4.0; x64)

uri: /xspj/api/subject/activity/orgs
method: POST

expected:
headers:

body:

statusCode: 201


actual:
statusCode: 422
headers:
    server: nginx/1.3.6
    date: Wed, 08 Jun 2016 01:34:04 GMT
    content-type: application/json;charset=utf-8
    content-length: 96
    connection: close
    set-cookie: JSESSIONID=5D00A2A396F0D2E422E20C48DAC093B4; Path=/xspj/; HttpOnly

body:
{"message":"验证失败","errors":{"field":"name","resource":"acitvity_org","code":"required"}}



complete: 0 passing, 1 failing, 0 errors, 0 skipped, 1 total
complete: Tests took 3333ms
complete: See results in Apiary at: https://app.apiary.io/public/tests/run/218584ba-889a-4e2c-b6f0-71c4968b0e6f
```

my apiblue file : 

```
## test post request  [POST /xspj/api/subject/activity/orgs]

+ Attributes
    + name: '456' (string) - name

+ Request (application/x-www-form-urlencoded;charset=UTF-8)

    + Headers

            Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE0NjUzNjMyNTksImlzcyI6IjBkYzQyM2YyZGYzYjRlNDJiZDI4NzFkZjczMWY2MjdiIn0.DwM2ez07Y5bLfG5ZvYQKSDCJX_jvV_OgrsUxp32uQG4

+ Response 201

```

**Comment by honzajavorek** [comment]
Hi, which version of Dredd are you using?

**Comment by netmilk** [comment]
Hey @paddingme,

Thank you for giving Dredd a try! When you leave the media type empty in the response Dredd is setting expected media type to default `text/plain`. Your server is returning `content-type: application/json;charset=utf-8`, please try to add it to the response in the blueprint like this:

```
+ Response 201 (content-type: application/json;charset=utf-8)
```

@paddingme, would you mind letting me know if this workaround solution helped?


@honzajavorek We should question if the current behavior is correct and if the validation of the body should be performed even though the body is not present in the API Blueprint.

**Comment by honzajavorek** [comment]
Ha! I was wondering how the header mismatch happened, hence I asked for Dredd version to find out if it's not regression. I didn't notice it's **response** content type, not request.

Not validating at all if body isn't present would probably solve also https://github.com/apiaryio/dredd/issues/468. I think we should:

- Provide warning if we assume `text/plain`.
- Provide warning if there is no body specified in API description unless the status code is 204.
- Continue validation even though the body isn't present.

If it's 204, people shouldn't specify content type, Dredd defaults to `text/plain` and empty body will equal to empty body. Everything will pass.

If it isn't 204, then body shouldn't be empty or if it intentionally is empty string, then the content type should be set correctly to text/plain. Everything will pass too.

**Comment by paddingme** [comment]
Thank your great job  and  your fast and detailed answer @netmilk @honzajavorek .

My version of Dredd is v1.0.11.

and I tried with @netmilk 's suggestion:

```
+ Response 201 (content-type: application/json;charset=utf-8)
``` 
But  it didn't work.
```
fail: POST /xspj/api/subject/activity/orgs duration: 271ms
fail:
request:
body:
headers:
    Content-Type: application/x-www-form-urlencoded;charset=UTF-8
    Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE0NjUzNjMyNTksImlzcyI6IjBkYzQyM2YyZGYzYjRlNDJiZDI4NzFkZjczMWY2MjdiIn0.DwM2ez07Y5bLfG5ZvYQKSDCJX_jvV_OgrsUxp32uQG4
    User-Agent: Dredd/1.0.11 (Darwin 15.4.0; x64)
uri: /xspj/api/subject/activity/orgs
method: POST
expected:
headers:
    Content-Type: content-type: application/json;charset=utf-8

body:
statusCode: 201
actual:
statusCode: 401
headers:
    server: nginx/1.3.6
    date: Sun, 12 Jun 2016 04:41:10 GMT
    content-type: text/html;charset=utf-8
    content-length: 39
    connection: close

body:
{"msg":"验证失败","success":false}

complete: 0 passing, 0 failing, 1 errors, 0 skipped, 1 total
complete: Tests took 2018ms
complete: See results in Apiary at: https://app.apiary.io/public/tests/run/0cb42ae2-6a87-4f4c-b4f4-d322f4a42f23
```
Finally I found that my backend server cannot receive resquest's body content, I fixed it as following:

```
## test post request  [POST /xspj/api/subject/activity/orgs{?name}]

+ Parameters

    + name: `456222` (string) - name

+ Request (application/x-www-form-urlencoded;charset=UTF-8)

    + Headers

            Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE0NjUzNjMyNTksImlzcyI6IjBkYzQyM2YyZGYzYjRlNDJiZDI4NzFkZjczMWY2MjdiIn0.DwM2ez07Y5bLfG5ZvYQKSDCJX_jvV_OgrsUxp32uQG4

+ Response 201
```

then this post api is passed.

```
$ dredd
info: Configuration dredd.yml found, ignoring other arguments.
info: Using apiary reporter.
warn: Apiary reporter environment variable APIARY_API_KEY or APIARY_API_NAME not defined.
info: Beginning Dredd testing...
complete: Tests took 2206ms
complete: See results in Apiary at: https://app.apiary.io/public/tests/run/4a9cde5c-d025-49e1-a382-8cc25cff5e9c
```
