### ISSUE TITLE
[Feature request] Add an output format option

### ISSUE THREAD

**Issue by aledeg** [apiaryio/dredd#593]
Unlike many tools available, I cannot have a nice progress output with dredd on CLI.

I am thinking of a dot progress like you can find with tools like behat or phpunit.
We could have something like:
```
.....F..E...S............F..E...S............F..E...S................. 70
...............F..E...S............F..E...S............F..E...S....... 140
.....
145 tests (121 passed, 6 failed, 6 errored, 6 skipped)
```

This would be great especially when using with travis.

Bonus will be with colors :)

**Comment by ecordell** [comment]
I think you want the `--reporter=dot` argument to get that output. Other options are:  junit, nyan, dot, markdown, html, and apiary. See: https://dredd.readthedocs.io/en/latest/usage-cli/#-reporter-r

**Comment by honzajavorek** [comment]
Ha, I forgot about `--reporter=dot`. @aledeg Would that work for you?

**Comment by aledeg** [comment]
@ecordell I wasn't aware of that option. Good catch!
@honzajavorek Sure! as soon as I can make it work. So far, no luck.

**Comment by aledeg** [comment]
I think the dot reporter is not working. Dredd stall when used with that reporter.

**Comment by aledeg** [comment]
I am using the dot reporter, but for some reason, the output is not what I am expecting.

Instead of having something like
```
...F..
```
I have something like:
```
[Tue Aug 23 11:51:39 2016] 127.0.0.1:44062 [200]: /dredd.php/book
.[Tue Aug 23 11:51:39 2016] 127.0.0.1:44062 [201]: /dredd.php/book
.[Tue Aug 23 11:51:39 2016] 127.0.0.1:44062 [400]: /dredd.php/book
.[Tue Aug 23 11:51:39 2016] 127.0.0.1:44062 [200]: /dredd.php/book/1
F[Tue Aug 23 11:51:39 2016] 127.0.0.1:44062 [400]: /dredd.php/book/1
```

How should I configure dredd to get the output I'd like?

**Comment by honzajavorek** [comment]
Seems like a bug to me. My fault, I should have better check if everything works as expected when closing #594.

Looks like the dot reporter never properly worked and you are digging it up from its tomb. I'm sorry for the issues, but many thanks for going through this! I'll try to look into it in following days.

**Comment by aledeg** [comment]
@honzajavorek Thanks!

**Comment by honzajavorek** [comment]
@aledeg I wasn't able to reproduce this. What exactly is your setup? This is what I get:

```
$ dredd apiary.apib http://example.com --reporter=dot
info: Beginning Dredd testing...
F..F.F
info: Displaying failed tests...
fail: POST /machines duration: 336ms
...
```

How do you run Dredd, what is your `dredd.yml`, version, etc.? Do you use [`--level`](http://dredd.readthedocs.io/en/latest/usage-cli/#-level-l)?

**Comment by aledeg** [comment]
@honzajavorek I use dredd 2.0

Here is my config file:
```yaml
dry-run: null
hookfiles: [tests/dredd/*Hook.php]
language: vendor/bin/dredd-hooks-php
sandbox: false
server: 'php -S 127.0.0.1:8888 -t web/'
server-wait: 3
init: true
custom: {}
names: false
only: []
reporter: dot
output: []
header: []
sorted: false
user: null
inline-errors: false
details: false
method: []
color: true
level: info
timestamp: false
silent: false
path: []
hooks-worker-timeout: 50000
hooks-worker-connect-timeout: 15000
hooks-worker-connect-retry: 500 
hooks-worker-after-connect-wait: 1000
hooks-worker-term-timeout: 50000
hooks-worker-term-retry: 500 
hooks-worker-handler-host: localhost
hooks-worker-handler-port: 61321
blueprint: apiary.apib
endpoint: 'http://127.0.0.1:8888/app_dredd.php'
```

When I wrote that ticket, it was with the previous stable version. But I did reproduced the same behavior. It might be linked to my environment though.
I run it on ```Ubuntu 16.04```, with ```Bash 4.3.46```. I either use ```Terminator 0.98``` or ```GNOME terminal 3.18.3```.
