### ISSUE TITLE
Find a way how to work with binary files in hooks

### ISSUE THREAD

**Issue by aledeg** [apiaryio/dredd#617]
I don't know if I should open that ticket here or [here](https://github.com/ddelnano/dredd-hooks-php).

I am trying to change the request body with the content of a file with a hook, but it does not work.
I have the following error:

```
SyntaxError: Unexpected end of input
  at Object.parse (native)
  at Socket.<anonymous> (/usr/lib/node_modules/dredd/lib/hooks-worker-client.js:268:34)
  at emitOne (events.js:90:13)
  at Socket.emit (events.js:182:7)
  at readableAddChunk (_stream_readable.js:153:18)
  at Socket.Readable.push (_stream_readable.js:111:10)
  at TCP.onread (net.js:534:20)
```

This is what I have in my hook:

``` php
$transaction->request->body = file_get_contents($filename);
```

Is this the good way of doing that?

Ping @ddelnano

**Comment by ddelnano** [comment]
@aledeg can you give more information about the http request you are trying to send??  What the type of file this is, content type of the req should be, etc.

**Comment by aledeg** [comment]
@ddelnano here is the information you wanted.

- method used: POST
- type of file: jpeg image
- content type: image/*

Here is the actual image used for the tests:
![default](https://cloud.githubusercontent.com/assets/3056148/18082093/8f46b300-6e9d-11e6-8c14-44673e0cb144.jpg)

I know that my api is working because I've tested it with behat and manually. It seems limited to dredd so far.

**Comment by aledeg** [comment]
@honzajavorek Any insight about that issue?

**Comment by honzajavorek** [comment]
@aledeg We're still missing a good canonical example for sending/testing binary data in Dredd using hooks. It's on my roadmap to prepare related examples, write tests for them so we're sure Dredd really works the way we recommend and put them to documentation. Related issues: #52 #87 and maybe even more.

From what you shared I can't tell exactly whether it's PHP hook handler issue, Dredd issue or issue in your hooks. Please try to investigate further what exactly might be happening so we can take a closer look.

- What command line options do you use? `$ dredd ( write your CLI options here )`
- What is in your `dredd.yml`?
- What's your `dredd --version` output?
- Does `dredd --level=debug` uncover something?

**Comment by aledeg** [comment]
@honzajavorek I've made some more tests. Here is what I've got now.

* error message:
```
SyntaxError: Unexpected end of JSON input
  at Object.parse (native)
  at Socket.<anonymous> (/usr/lib/node_modules/dredd/lib/hooks-worker-client.js:279:34)
  at emitOne (events.js:96:13)
  at Socket.emit (events.js:188:7)
  at readableAddChunk (_stream_readable.js:176:18)
  at Socket.Readable.push (_stream_readable.js:134:10)
  at TCP.onread (net.js:548:20)
```
* ```dredd --version``` output:
```
dredd v2.2.3 (Linux 4.4.0-45-generic; x64)
```
* cli options:
```
dredd --config tests/dredd.yml --level silly
```
* ```dredd.yml``` content:
```yaml
dry-run: null
hookfiles:
  - tests/Hook.php
language: vendor/bin/dredd-hooks-php
sandbox: false
server: 'bin/console server:start 127.0.0.1:8888 --force --quiet --env=test'
server-wait: 3
init: true
custom: {}
names: false
only: []
reporter:
  - apiary
  - dot
output: []
header: []
sorted: false
user: null
inline-errors: false
details: false
method: []
color: true
level: complete
timestamp: false
silent: false
path: []
hooks-worker-timeout: 50000
hooks-worker-connect-timeout: 15000
hooks-worker-connect-retry: 500
hooks-worker-after-connect-wait: 1000
hooks-worker-term-timeout: 50000
hooks-worker-term-retry: 500
hooks-worker-handler-host: localhost
hooks-worker-handler-port: 61321
blueprint: [test.apib]
endpoint: 'http://127.0.0.1:8888/app_dredd.php'
```
* Hook content:
```php
Hooks::before('Test picture', function (&$transaction) {
        $transaction->request->body = file_get_contents('dredd/default.jpg');
});
```
* Apib content:
```md
### Add picture [POST /picture]

+ Request (image/*)

+ Response 204
```

For what I understand, it looks like dredd is expecting JSON in the request. But obviously, I didn't provide some since I am pushing an image.
Digging in the code, I found [this](https://github.com/apiaryio/dredd/blob/master/src/hooks-worker-client.coffee#L257). It probably is the root of the problem.
