### ISSUE TITLE
Required body parameter not included in request

### ISSUE THREAD

**Issue by timrcoulson** [apiaryio/dredd#649]
Looks like the 'required' email body param in our user sign up request is not consistently sent by Dredd in the latest version.

```
$dredd spec.yaml $BASE_URL
```

Here's the request we send:

``` yaml
  /auth/register/:
     post:
      summary: Register new user
      produces:
        - application/json
      consumes:
        - application/json
      parameters:
        - name: body
          in: body
          description: The email of the user
          required: true
          schema:
            $ref: "#/definitions/RegisterRequest"
      responses:
        200:
          description: New User profile details
          schema:
            properties:
              data:
                $ref: "#/definitions/Register"
        422:
          description: Route not found
          schema:
            $ref: '#/definitions/Error'
```

Def:

``` yaml
RegisterRequest:
    required:
      - email
    properties:
      email: 
        type: string
        format: email
      password:
        type: string
        format: password
      first_name:
        type: string
        pattern: ^[a-zA-Z]+$
      last_name:
        type: string
        pattern: ^[a-zA-Z]+$
```

On the latest version, our API complains the email hasn't been sent. If we downgrade to 2.2.1, the issue disappears.

```
+ dredd --version
dredd v2.2.2 (Linux 3.13.0-85-generic; x64)
```

**Comment by timrcoulson** [comment]
Went down the dep chain and looks like it's related to an update of fury-adapter

**Comment by honzajavorek** [comment]
Hi @timrcoulson, thanks for reporting this. So this is regression from 2.2.1 to 2.2.2. The list of related changes is here: https://github.com/apiaryio/dredd/pull/646 I went through all of them, but I wasn't able to identify exactly which one of the Fury adapter changes broke the behavior. @pksunkara @kylef could you help, please?

**Comment by timrcoulson** [comment]
Thanks for digging into it guys. I found the issue/feature(!) and it's not related to those commits.
It was something happening intermittently, and here's why:
In my request, only the email was required; meaning that password, first_name and last_name would appear intermittently in test runs:
```
RegisterRequest:
    required:
      - email
    properties:
      email: 
        type: string
        format: email
      password:
        type: string
        format: password
      first_name:
        type: string
        pattern: ^[a-zA-Z]+$
      last_name:
        type: string
        pattern: ^[a-zA-Z]+$
```
Whenever password was included, the entire request body was dropped (perhaps some security feature?). I could repro this simply by making password the only required field.
