### ISSUE TITLE
Is my dredd.yml not being read? 

### ISSUE THREAD

**Issue by bkuhl** [apiaryio/dredd#653]
Filing a bug report? :bug:

Despite passing a config file, it still asks for an endpoint and blueprint file.

#### What command line options do you use?

```
$ dredd --config=/var/www/html/dredd.yml
```

#### What is in your `dredd.yml`?

```yaml
dry-run: null
hookfiles: null
language: php
sandbox: false
server: null
server-wait: 3
init: false
custom: {}
names: false
only: []
reporter: []
output: []
header: [Api-Key: xxxxxxxxxxxxxxxxxx]
sorted: false
user: null
inline-errors: false
details: false
method: []
color: true
level: info
timestamp: false
silent: false
path: []
hooks-worker-timeout: 5000
hooks-worker-connect-timeout: 1500
hooks-worker-connect-retry: 500
hooks-worker-after-connect-wait: 100
hooks-worker-term-timeout: 5000
hooks-worker-term-retry: 500
hooks-worker-handler-host: localhost
hooks-worker-handler-port: 61321
blueprint: /var/www/html/resources/docs/api-documentation.apib
endpoint: 'http://web/api/v1'
```

#### What's your `dredd --version` output?

```
Native thread-sleep not available.
This will result in much slower performance, but it will still work.
You should re-install spawn-sync or upgrade to the lastest version of node if possible.
Check /usr/local/lib/node_modules/dredd/node_modules/spawn-sync/error.log for more details
dredd v1.0.9
```

#### Does `dredd --level=debug` uncover something?

No

#### Can you send us failing test in a Pull Request?

No
