### ISSUE TITLE
Including other files

### ISSUE THREAD

**Issue by stefan-endouble** [apiaryio/dredd#657]
Is there a way to configure dredd to include files? 

Tried to use the comments used by [aglio](https://gist.github.com/zdne/5f8295642af18aff27ec) but of course don't work :).

Some more info about working with multiple files: https://gist.github.com/zdne/5f8295642af18aff27ec. 

#### What command line options do you use?

```
$ dredd
```

#### What is in your `dredd.yml`?

```yaml
dry-run: null
hookfiles: null
language: nodejs
sandbox: false
server: null
server-wait: 3
init: false
custom: {}
names: false
only: []
reporter: [markdown]
output: [dredd.out.md]
header: []
sorted: false
user: null
inline-errors: false
details: false
method: []
color: true
level: info
timestamp: false
silent: false
path: []
hooks-worker-timeout: 5000
hooks-worker-connect-timeout: 1500
hooks-worker-connect-retry: 500
hooks-worker-after-connect-wait: 100
hooks-worker-term-timeout: 5000
hooks-worker-term-retry: 500
hooks-worker-handler-host: localhost
hooks-worker-handler-port: 61321
config: ./dredd.yml
blueprint: docs.apib
endpoint: 'http://some.stage.domain.tld:8080'
```

#### What's your `dredd --version` output?

```
dredd v2.2.3 (Darwin 15.6.0; x64)
```

#### Does `dredd --level=debug` uncover something?
```
// docs.apib:4 <!-- include(common_data_structures.apib) -->
warn: Parser warning in file 'docs.apib': (warning code 5) ignoring unrecognized block on line 4
```
#### Can you send us failing test in a Pull Request?
yes, just create a file with 
``` 
<!-- include(some_doc.apib) -->
```
