### ISSUE TITLE
The example value can't be set to the value specified "required" and "boolean" in "Parameter"

### ISSUE THREAD

**Issue by motoyasu-saburi** [apiaryio/dredd#677]
The example value can't be set to the value specified "required" and "boolean" in "Parameter".

This pattern is not work .
```
### GET /api/job{?boolParam}

+ Parameters
    + boolParam: false (required, boolean) - not work
    + boolParam: `false` (required, boolean) - not work
    + boolParam: "false" (required, boolean) - not work

+ Response 200
...
```

but, This pattern is working.
```
### GET /api/job{?boolParam}

+ Parameters
    + boolParam: false (required, string) - this type is boolean...
    + boolParam: `false` (required, string) - this type is boolean...
    + boolParam: "false" (required, string) - this type is boolean...

+ Response 200
...
```

#### What is in your `dredd.yml`?

```yaml
dry-run: null
hookfiles: ./hook.js
language: nodejs
sandbox: false
server: null
server-wait: 3
init: false
custom: {}
names: false
only: []
reporter: []
output: []
header: []
sorted: false
user: null
inline-errors: false
details: false
method: []
color: true
level: info
timestamp: false
silent: false
path: []
hooks-worker-timeout: 5000
hooks-worker-connect-timeout: 1500
hooks-worker-connect-retry: 500
hooks-worker-after-connect-wait: 100
hooks-worker-term-timeout: 5000
hooks-worker-term-retry: 500
hooks-worker-handler-host: localhost
hooks-worker-handler-port: 61321
config: ./dredd.yml
blueprint: document.apib
endpoint: 'http://localhost:8080'
```

#### What's your `dredd --version` output?

```
3.10.9
```
