### ISSUE TITLE
gzip encoding not decoded properly in dredd

### ISSUE THREAD

**Issue by yuriabaevzooz** [apiaryio/dredd#698]
#### Describe your problem
My requests to the service being sent with Accept-Encoding: gzip header. which means the response results in a  gzip encoding format, which in dredd are shown as question marks

when I dont send requests with Accept-Encoding: gzip header dredd decodes the result as expected.

#### What command line options do you use?

```
$ dredd 
```

#### What is in your `dredd.yml`?

```yaml
reporter: apiary
custom:
  apiaryApiKey: *****
  apiaryApiName: *****
dry-run: null
hookfiles: ./hook.js
language: nodejs
sandbox: false
server: null
server-wait: 3
init: false
names: false
only: []
output: []
header: []
sorted: false
user: null
inline-errors: false
details: false
method: []
color: true
level: info
timestamp: false
silent: false
path: []
hooks-worker-timeout: 5000
hooks-worker-connect-timeout: 1500
hooks-worker-connect-retry: 500
hooks-worker-after-connect-wait: 100
hooks-worker-term-timeout: 5000
hooks-worker-term-retry: 500
hooks-worker-handler-host: localhost
hooks-worker-handler-port: 61321
config: ./dredd.yml
blueprint: ./api-description.yml
endpoint: "*********"
```

#### What's your `dredd --version` output?

```
2.2.5
```

#### Can you send us failing test in a Pull Request?
i

fail: body: Real body "Content-Type" header is "application/json;charset=UTF-8" but body is not a parsable JSON.
Parse error on line 1:
��	�0
          �U
^
Expecting 'STRING', 'NUMBER', 'NULL', 'TRUE', 'FALSE', '{', '[', got 'undefined'
