### ISSUE TITLE
Error connecting to server under test when server on localhost

### ISSUE THREAD

**Issue by karpilin** [apiaryio/dredd#721]
#### Describe your problem
Each test is failing with the following error:
```
error: Error connecting to server under test!
````

Despite the api endpoint is set to `http://localhost:8000` , the api calls are sent to `http://127.0.0.1:8000`.

Running a web server on `127.0.0.1` instead of `localhost` solves the problem.

#### What command line options do you use?

```
$ dredd
```

#### What is in your `dredd.yml`?

```yaml
reporter: apiary
custom:
  apiaryApiKey: *******
  apiaryApiName: ********
dry-run: null
hookfiles: './hooks.php'
language: 'bin/dredd-hooks-php'
sandbox: false
server:
server-wait: 3
init: false
names: false
only: []
output: []
header: []
sorted: false
user: null
inline-errors: false
details: false
method: []
color: true
level: info
timestamp: false
silent: false
path: []
hooks-worker-timeout: 5000
hooks-worker-connect-timeout: 1500
hooks-worker-connect-retry: 500
hooks-worker-after-connect-wait: 100
hooks-worker-term-timeout: 5000
hooks-worker-term-retry: 500
hooks-worker-handler-host: localhost
hooks-worker-handler-port: 61321
config: ./dredd.yml
blueprint: api.apib
endpoint: 'http://localhost:8000/api/v1'
```

#### What's your `dredd --version` output?

```
dredd v2.2.5 (Darwin 15.6.0; x64)
```

#### Does `dredd --level=debug` uncover something?

```
debug: Evaluating results of transaction execution #1: Authorisation > Logout > Logout
debug: No emission of test data to reporters { Error: connect ECONNREFUSED 127.0.0.1:8000
    at Object.exports._errnoException (util.js:1028:11)
    at exports._exceptionWithHostPort (util.js:1051:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1090:14)

  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 8000 }
```
