### ISSUE TITLE
Dredd carriage return

### ISSUE THREAD

**Issue by m1ome** [apiaryio/dredd#753]
#### Describe your problem

Using `.apib` file (Part of it included):
```
# POST

+ Request (application/x-www-form-urlencoded)

    + Headers

            X-Api-Key: 54c2f20bb32f78db0066a97b858fxxxx

    + Body

            amount_currency=BTC&amount=0.01&from_account=f4f787a2-78f4-49ed-ba41-e475ab4407cf&to_account=aaef9728-bac9-4a8d-8649-8f14bbf75d89

+ Response 201 (application/json)

    + Body

            {
                "id":"82b03fcb-168d-4757-bae0-d28977f836e5"
            }
```

With this request Dredd adds `0a` carriage return symbol.
That's mean last variable `to_account` passed to API like `to_account\r`

Workaround:
```
amount_currency=BTC&amount=0.01&from_account=f4f787a2-78f4-49ed-ba41-e475ab4407cf&to_account=aaef9728-bac9-4a8d-8649-8f14bbf75d89&
```

Seems to me like a bug in **Dredd**.
Because not all API's use sanitize.

#### What command line options do you use?

```
$ dredd
```

#### What is in your `dredd.yml`?

```yaml
dry-run: null
hookfiles: null
language: nodejs
sandbox: false
server: null
server-wait: 3
init: false
names: false
only: []
output: []
header: []
sorted: false
user: null
inline-errors: false
details: false
method: []
color: true
level: info
timestamp: false
silent: false
path: []
hooks-worker-timeout: 5000
hooks-worker-connect-timeout: 1500
hooks-worker-connect-retry: 500
hooks-worker-after-connect-wait: 100
hooks-worker-term-timeout: 5000
hooks-worker-term-retry: 500
hooks-worker-handler-host: 127.0.0.1
hooks-worker-handler-port: 61321
config: ./dredd.yml
blueprint: build/apiary.apib
endpoint: 'https://127.0.0.1:62541/api/v2'
```

#### What's your `dredd --version` output?

```
( paste your output here )
```

#### Does `dredd --level=debug` uncover something?
No

#### Can you send us failing test in a Pull Request?
It described above.
