### ISSUE TITLE
When a config file is present, adding headers via command line with -h doesn't work

### ISSUE THREAD

**Issue by Simulalex** [apiaryio/dredd#757]
#### Describe your problem
I have a dredd.yml file with my project specific configurations but I have to pass in a header argument from our CI pipeline. When I use the --header argument it works correctly, but when I use -h, the header is ignored.

#### What command line options do you use?
Works:
```
$ dredd --config documentation/dredd.yml --header "foo:bar"
```
Doesn't work:
```
$ dredd --config documentation/dredd.yml -h "foo:bar"
```
#### What is in your `dredd.yml`?

```yaml
dry-run: null
hookfiles: documentation/hooks_oauth.js
language: nodejs
sandbox: false
server: null
server-wait: 3
init: false
custom: {}
names: false
only: []
reporter: []
output: []
header: []
sorted: false
user: null
inline-errors: false
details: false
method: []
color: true
level: info
timestamp: false
silent: false
path: []
hooks-worker-timeout: 5000
hooks-worker-connect-timeout: 1500
hooks-worker-connect-retry: 500
hooks-worker-after-connect-wait: 100
hooks-worker-term-timeout: 5000
hooks-worker-term-retry: 500
hooks-worker-handler-host: localhost
hooks-worker-handler-port: 61321
config: ./dredd.yml
blueprint: documentation/api-description.apib
endpoint: 'https://my.end.point'
```

#### What's your `dredd --version` output?

```
dredd v2.2.5 (Darwin 15.6.0; x64)
```
