### ISSUE TITLE
When Done isn't called, Dredd process exits 0

### ISSUE THREAD

**Issue by liront2** [apiaryio/dredd#771]
#### Describe your problem

Assuming that Done isn't called in one of the hooks, Dredd stdout will be cut in the middle with process.exit(0). Since this is an error, process exit of Dredd should be between 1-255.

#### What command line options do you use?

none

#### What is in your `dredd.yml`?

```yaml
reporter: apiary
custom:
dry-run: null
hookfiles: ./hooks.js
language: nodejs
sandbox: false
server: null
server-wait: 3
init: false
names: false
only: []
output: []
header: []
sorted: false
user: null
inline-errors: false
details: false
method: []
color: true
level: info
timestamp: false
silent: false
path: []
hooks-worker-timeout: 5000
hooks-worker-connect-timeout: 1500
hooks-worker-connect-retry: 500
hooks-worker-after-connect-wait: 100
hooks-worker-term-timeout: 5000
hooks-worker-term-retry: 500
hooks-worker-handler-host: localhost
hooks-worker-handler-port: 61321
config: ./dredd.yml
blueprint: ./testingSwagger.yaml
endpoint: 'https://google.com'
```

#### What's your `dredd --version` output?

```
dredd v2.1.1 (Darwin 16.3.0; x64)
```

#### Does `dredd --level=debug` uncover something?

no
