### ISSUE TITLE
Dredd doesn't kill server when started from bash script

### ISSUE THREAD

**Issue by ericgriffis** [apiaryio/dredd#793]
#### Describe your problem

I need to start my Unicorn+Sinatra server with an environment variable. As suggested in https://github.com/apiaryio/dredd/issues/554, I set the environment variable in a shell script and used that to start my server with dredd. However, dredd doesn't kill the server on exit, leaving me to find the process and kill it each time.

I created a minimal example to reproduce: https://github.com/ericgriffis/dredd_sinatra_example

The first time I run `dredd` (using yml config), it runs fine. The second time, I see errors when dredd tries to start the server since the server from the previous run is still alive:

```
E, [2017-05-26T13:39:52.590851 #90324] ERROR -- : adding listener failed addr=0.0.0.0:8081 (in use)
E, [2017-05-26T13:39:52.590935 #90324] ERROR -- : retrying in 0.5 seconds (4 tries left)
E, [2017-05-26T13:39:53.092481 #90324] ERROR -- : adding listener failed addr=0.0.0.0:8081 (in use)
E, [2017-05-26T13:39:53.092546 #90324] ERROR -- : retrying in 0.5 seconds (3 tries left)
E, [2017-05-26T13:39:53.597173 #90324] ERROR -- : adding listener failed addr=0.0.0.0:8081 (in use)
E, [2017-05-26T13:39:53.597233 #90324] ERROR -- : retrying in 0.5 seconds (2 tries left)
E, [2017-05-26T13:39:54.102149 #90324] ERROR -- : adding listener failed addr=0.0.0.0:8081 (in use)
E, [2017-05-26T13:39:54.102207 #90324] ERROR -- : retrying in 0.5 seconds (1 tries left)
E, [2017-05-26T13:39:54.607209 #90324] ERROR -- : adding listener failed addr=0.0.0.0:8081 (in use)
E, [2017-05-26T13:39:54.607288 #90324] ERROR -- : retrying in 0.5 seconds (0 tries left)
E, [2017-05-26T13:39:55.108813 #90324] ERROR -- : adding listener failed addr=0.0.0.0:8081 (in use)
```

#### What command line options do you use?

N/A

#### What is in your `dredd.yml`?

From [repo above](https://github.com/ericgriffis/dredd_sinatra_example):

```yaml
dry-run: null
hookfiles: null
language: nodejs
sandbox: false
server: scripts/start_test_server.sh
server-wait: 3
init: false
custom: {}
names: false
only: []
reporter: []
output: []
header: []
sorted: false
user: null
inline-errors: false
details: false
method: []
color: true
level: info
timestamp: false
silent: false
path: []
hooks-worker-timeout: 5000
hooks-worker-connect-timeout: 1500
hooks-worker-connect-retry: 500
hooks-worker-after-connect-wait: 100
hooks-worker-term-timeout: 5000
hooks-worker-term-retry: 500
hooks-worker-handler-host: 127.0.0.1
hooks-worker-handler-port: 61321
config: ./dredd.yml
blueprint: swagger.yml
endpoint: 'http://127.0.0.1:8081'
```

Script `script/start_test_server.sh` (again from [repo above](https://github.com/ericgriffis/dredd_sinatra_example)):

```
#!/bin/bash
export TEST=true
bundle exec unicorn -p 8081
```

#### What's your `dredd --version` output?

```
dredd v3.5.0 (Darwin 15.4.0; x64)
```

#### Does `dredd --level=debug` uncover something?

Dredd seems to think its killing the server just fine:

```
verbose: Dredd instance run finished.
verbose: Exiting Dredd process with status '0'.
debug: Using configured custom exit() method to terminate the Dredd process.
debug: The backend server process has already terminated
```

However, `lsof -i tcp:8081` reveals the process is still running, and subsequent runs of dredd show errors (included above) when attempting to start the server since the port is still in use.

#### Can you send us failing test in a Pull Request?

I'm willing to contribute but am unsure of what to test. Since the workaround in https://github.com/apiaryio/dredd/issues/554 apparently works for some people, I'm unsure if this issue is OS-specific or framework-specific or something else.

I would also be able to solve the same problem using https://github.com/apiaryio/dredd/pull/542, which was closed in favor of the workaround which doesn't work for me, and also apparently due to Windows incompatibility. I mention this since I'm open to other workarounds for this issue and am willing to contribute but am unsure of the best course or where to start.
