### ISSUE TITLE
Open API: Error as "[" is found

### ISSUE THREAD

**Issue by philsturgeon** [apiaryio/dredd#815]
#### Describe your problem

In the past I've tried getting square bracket arrays into API documentation, and API Blueprint does not support them. I've had to do:

``` md
- Parameters
    - `reservable_uuids*`: `346f297d-3bb1-7488-ad03-d345efc11784` (array, required) - UUIDs for desks, offices, etc.
```

Now I've switched over to Open API/Swagger v2.0 and it supports them! 

```
parameters:
      - name: 'reservable_uuids[]'
        in: query
        required: false
        type: array
        collectionFormat: multi
        items:
          type: string
          format: uuid
        x-example:
          - 346f297d-3bb1-7488-ad03-d345efc11784
```

Problem is, when I run dredd against this swagger file, dredd will complain that it's not valid. I assume this is due to things being converted into API Elements, and it's not quite as lax as Swagger is. 

#### Can you send us failing test in a Pull Request?

I'm not actually sure how to run tests. As far as I could tell, CONTRIBUTING.md doesn't explain it. It only talks about linting and other stuff.
