### ISSUE TITLE
Errors do not affect CLI exit code

### ISSUE THREAD

**Issue by clementgarnier** [apiaryio/dredd#818]
#### Describe your problem

Dredd CLI returns 0 when tests are errored, as long as none are failing, e.g.
```
complete: 0 passing, 0 failing, 1 errors, 0 skipped, 1 total
```

#### What command line options do you use?

```
$ dredd
```

#### What is in your `dredd.yml`?

```yaml
dry-run: null
hookfiles: null
language: nodejs
sandbox: false
server: /foo/bar/baz
server-wait: 3
init: false
custom: {}
names: false
only: []
reporter: []
output: []
header: []
sorted: false
user: null
inline-errors: false
details: false
method: []
color: true
level: info
timestamp: false
silent: false
path: []
hooks-worker-timeout: 5000
hooks-worker-connect-timeout: 1500
hooks-worker-connect-retry: 500
hooks-worker-after-connect-wait: 100
hooks-worker-term-timeout: 5000
hooks-worker-term-retry: 500
hooks-worker-handler-host: 127.0.0.1
hooks-worker-handler-port: 61321
config: ./dredd.yml
blueprint: sample_blueprint.md
endpoint: 'http://127.0.0.1:3000'
```

#### What's your `dredd --version` output?

```
dredd v4.1.1 (Darwin 16.6.0; x64)
```

#### Can you send us failing test in a Pull Request?

To reproduce, run dredd with above configuration; note `/foo/bar/baz` is voluntarily inexistent, which will fail to start the server and mark all tests as error. A `sample_blueprint.md` can be created with any valid blueprint (I used the first example [here](https://raw.githubusercontent.com/apiaryio/api-blueprint/master/examples/01.%20Simplest%20API.md)) but not required to reproduce, as a missing blueprint file will also trigger the error state.
