### ISSUE TITLE
:bug Conversion of hyphens to %2d in API documentation

### ISSUE THREAD

**Issue by gellati** [apiaryio/dredd#856]
If you want to share an idea :bulb:, feel free to delete all this and just write what you want. If you are reporting a bug :bug:, remove this paragraph and fill following:

#### Describe your problem

I am not sure if this is a bug...

Concerning this issue #460  , I've tried encoding hyphens (-) as %2d in query parameters, because some APIs are not compliant with [RFC 6570](https://tools.ietf.org/html/rfc6570). However, %2d is further encoded to %252d, i.e. the percentage sign is further encoded. Is this a bug in the library, or part of expected behaviour? Or does this issue stem from the [URI Template library](https://github.com/grncdr/uri-template).

I am trying to make a search query to an implementation of a healthcare API which provides this resource, the search/query parameter based-on can be seen at the bottom of the page: https://www.hl7.org/fhir/careplan.html

Converting hyphens to %2d might not be the best way to tackle this problem, but right now I would just like to know where error message originates from.

#### What command line options do you use?

```
$ dredd
```

#### What is in your `dredd.yml`?

```yaml
# documentation about options can be read in https://github.com/apiaryio/dredd/blob/master/src/options.coffee
dry-run: null #null, true
hookfiles: ./hooks/hook.*
language: nodejs
sandbox: false
server: null
server-wait: 3
init: false
custom: {}
names: false
only: []
reporter: []
output: []
header: []
sorted: false
user: null
inline-errors: false
method: []
color: true
level: verbose # verbose, info
timestamp: false
silent: false
path: []
hooks-worker-timeout: 5000
hooks-worker-connect-timeout: 1500
hooks-worker-connect-retry: 500
hooks-worker-after-connect-wait: 100
hooks-worker-term-timeout: 5000
hooks-worker-term-retry: 500
config: ./dredd.yml
blueprint: ./kapa-api/kapa-api.yaml
endpoint: 'https://localhost:6082'
#endpoint: 'https://oda.medidemo.fi'```

#### What's your `dredd --version` output?

```
dredd v4.1.2 (Linux 4.11.12-200.fc25.x86_64; x64)
```

#### Does `dredd --level=debug` uncover something?

Parameter not defined in API description document: based%252don

#### Can you send us failing test in a Pull Request?
