### ISSUE TITLE
Dredd doesn't follow $ref in JSON schema

### ISSUE THREAD

**Issue by yurrriq** [apiaryio/dredd#881]
#### Describe your problem

```

fail: body: At '/http:~1~1example.com~1schemas~1sanitized~1example.json' Missing schema
```

#### What command line options do you use?

```
$ dredd
```

#### What is in your `dredd.yml`?

```yaml
dry-run: null
hookfiles: null
language: ruby
sandbox: false
server: ./run
server-wait: 3
init: false
custom: {}
names: false
only: []
reporter: []
output: []
header: []
sorted: false
user: null
inline-errors: false
details: false
method: []
color: true
level: info
timestamp: false
silent: false
path: []
hooks-worker-timeout: 5000
hooks-worker-connect-timeout: 1500
hooks-worker-connect-retry: 500
hooks-worker-after-connect-wait: 100
hooks-worker-term-timeout: 5000
hooks-worker-term-retry: 500
hooks-worker-handler-host: 127.0.0.1
hooks-worker-handler-port: 61321
config: ./dredd.yml
blueprint: apib/delivery.apib.md
endpoint: 'http://127.0.0.1:4403'
```

#### What's your `dredd --version` output?

```
dredd v4.5.0 (Darwin 16.7.0; x64)
```

#### Does `dredd --level=debug` uncover something?

No.

#### Can you send us failing test in a Pull Request?

Not right now, but I could later, if necessary. A schema like the following should reproduce the issue:
```json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "example": {
      "$ref": "http://example.com/fixme/i/fail.json"
    }
  }
}
```
