### ISSUE TITLE
Misleading reporter name - JUnit/XUnit

### ISSUE THREAD

**Issue by felpel** [apiaryio/dredd#888]
#### Describe your problem

I'm trying to integrate Dredd in my continuous integration. In my configuration, if I specify `junit` as the reporter, it will output correctly the report in XML format. Although, if we look at the code in the repository, it is listed as `XUnitReporter`, which seems odd to me. It might be for backward compatibility, but I'm sure it will be confusing for new adepts like me.

#### What command line options do you use?

```
$ dredd
```

#### What is in your `dredd.yml`?

In order to make it work, I configured it this way:
```yaml
# other properties skipped
reporter: [junit]
output: [./reports/report.xml]
```
Although, I think it should be this way:
```yaml
# other properties skipped
reporter: [xunit]
output: [./reports/report.xml]
```

#### What's your `dredd --version` output?

```
dredd v4.4.0 (Windows_NT 10.0.14393; x64)
```

#### Does `dredd --level=debug` uncover something?

Not related to the command line call.

#### Can you send us failing test in a Pull Request?

The test outcome will simply not be reported in the `reports` folder.
