### ISSUE TITLE
How to find errors in python hooks

### ISSUE THREAD

**Issue by samekmichal** [apiaryio/dredd#910]
#### Describe your problem
Hi dredders, I am new to testing with dredd and, obviously, there is a problem with my hooks implemented in python; residing in hooks folder - referenced in dredd.yaml.
Execution of my tests always fail, due to timeouts - logs state basically only the following. 
```
warn: Hook handling timed out.
fail: POST (201) /users duration: 5003ms
```
When I don't let dredd execute the hooks, the test are performed successfully. Since the logs don't report any bugs in hooks (even with ```--level=silly```), can you advise a better way of finding bugs other than looking at the hooks code?

#### What command line options do you use?
No special commands.
```
$ dredd
```

#### What is in your `dredd.yml`?

```yaml
dry-run: null
hookfiles: hooks/*.py
language: python
sandbox: false
server: null
server-wait: 3
init: false
custom: {}
names: false
only: []
reporter: []
output: []
header: []
sorted: false
user: null
inline-errors: false
details: false
method: []
color: true
level: info
timestamp: false
silent: false
path: []
hooks-worker-timeout: 5000
hooks-worker-connect-timeout: 5000
hooks-worker-connect-retry: 500
hooks-worker-after-connect-wait: 100
hooks-worker-term-timeout: 5000
hooks-worker-term-retry: 500
hooks-worker-handler-host: 127.0.0.1
hooks-worker-handler-port: 61321
config: ./dredd.yml
blueprint: sindiko.apib
endpoint: '....' //substituted by real url
```

#### What's your `dredd --version` output?

```
redd v4.6.2 (Darwin 16.7.0; x64)
```

#### Does `dredd --level=debug` uncover something?
verbose: Starting TCP connection with hooks handler process.
info: Successfully connected to hooks handler. Waiting 0.1s to start testing.
verbose: Registering hooks.
verbose: Executing HTTP transactions
verbose: Running 'beforeAll' hooks
debug: Running hooks...
verbose: Sending HTTP transaction data to hooks handler: 618c5350-9bb2-4a55-b78d-54f6c2676112
info: Hooks handler stderr:
Connection closed

#### Can you send us failing test in a Pull Request?
Sure, later if needed.
