### ISSUE TITLE
RangeError while skipping a lot of transactions in a JS hook

### ISSUE THREAD

**Issue by juliengerboud** [apiaryio/dredd#957]
#### Describe your problem
When skipping an important number of transaction (all of them actually) in a JS hook, I get a 
`RangeError: Maximum call stack size exceeded` and `RangeError: Invalid array length`

[test-files.zip](https://github.com/apiaryio/dredd/files/1664520/test-files.zip)

#### What command line options do you use?

```
$ dredd --config dredd.yml
```

#### What is in your `dredd.yml`?

```yaml
dry-run: null
hookfiles: [/home/hooks/hook_test.js]
language: nodejs
sandbox: false
server: null
server-wait: 3
init: false
custom: {}
names: false
only: []
reporter: [html]
output: [Report.html]
header: []
sorted: false
user: null
inline-errors: false
details: false
method: []
color: true
level: debug
timestamp: false
silent: false
path: []
hooks-worker-timeout: 5000
hooks-worker-connect-timeout: 1500
hooks-worker-connect-retry: 500
hooks-worker-after-connect-wait: 100
hooks-worker-term-timeout: 5000
hooks-worker-term-retry: 500
hooks-worker-handler-host: 127.0.0.1
hooks-worker-handler-port: 61321
config: ./dredd.yml
blueprint: ./test-api.yaml
endpoint: http://172.18.0.1:8080
```

#### What's your `dredd --version` output?

```
dredd v4.9.3 (Linux 4.4.0-112-generic; x64)
```

#### Does `dredd --level=debug` uncover something?
It seems that, dredd is processing several test before evaluating them, could that be the cause? 

#### Can you send us failing test in a Pull Request?
I have attached the Swagger file, the output logs and the hook I am using to skip the transaction. I guess, that will allow you to reproduce the bug
